language: csharp
mono: none
dotnet: 2.2

install:
  # - choco install "msbuild-sonarqube-runner" -y
  dotnet tool install --global dotnet-sonarscanner

script:
  dotnet sonarScanner begin /k:"Taskin" /d:sonar.organization="juanluelguerre-github" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="%token%" /d:sonar.language="cs" /d:sonar.cs.opencover.reportsPaths=./test/ElGuerre.Taskin.Api.Services.Tests/coverage.opencover.xm /d:sonar.exclusions=**wwwroot/lib/**,**/test/**,**/*Mock.cs"
  # dotnet restore %sln%
  dotnet build ElGuerre.Taskin.Full.sln /t:Rebuild
  dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=\"opencover\" ./test/ElGuerre.Taskin.Api.Services.Tests/ElGuerre.Taskin.Api.Services.Tests.csproj
  dotnet sonarscanner end /d:sonar.login="%token%"