language: csharp
mono: none
dotnet: 2.2
solution: ElGuerre.Taskin.Full.sln

install:
  nuget restore ElGuerre.Taskin.Full.sln
  dotnet tool install --global dotnet-sonarscanner

script:
  dotnet sonarScanner begin /k:"Taskin" /d:sonar.organization="juanluelguerre-github" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="%SONAR_TOKEN%" /d:sonar.language="cs" /d:sonar.cs.opencover.reportsPaths=./test/ElGuerre.Taskin.Api.Tests/coverage.opencover.xml /d:sonar.exclusions=**/*.bin,**wwwroot/lib/**,**/test/**,**/*Mock.cs
  dotnet build ElGuerre.Taskin.Full.sln /t:Rebuild
  dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=\"opencover\" ./test/ElGuerre.Taskin.Api.Tests/ElGuerre.Taskin.Api.Tests.csproj
  dotnet sonarscanner end /d:sonar.login="%SONAR_TOKEN%"
